# Generated by Django 2.2.16 on 2022-03-27 18:26

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0006_follow'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True,
                                                             user=django.db.models.expressions.F(
                                                                 'author')),
                                              name='user_is_not_author'),
        ),
    ]
